{{- $nonEmpty := dict }}
{{- range $k, $v := .Values.secretEnv }}{{ if $v }}{{ $_ := set $nonEmpty $k $v }}{{ end }}{{ end }}
{{- if and (not .Values.existingSecret) $nonEmpty }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
{{- range $k, $v := $nonEmpty }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
