// Company Profile Analyzer - Main Orchestrator
// Combines all intelligence gathering services
// All threshold detection will be done dynamically via reasoning model + FDA/CPSC API

import type {
  CompanyInput,
  CompanyProfile,
  CompanyIntelligence,
  RegulatoryThresholds,
  DataQuality,
  DataSource
} from './types.ts';
import { webScrapingService } from './web-scraper.ts';

export class CompanyAnalyzer {
  /**
   * Main entry point - analyzes company and returns intelligence
   * TODO: Thresholds and recommendations will be generated dynamically
   * via reasoning model + FDA/CPSC API
   */
  async analyzeCompany(input: CompanyInput): Promise<CompanyIntelligence> {
    console.log(`Starting company analysis for: ${input.companyName}`);

    try {
      // Step 1: Build company profile (gathers data from public sources)
      const profile = await this.buildCompanyProfile(input);

      // Step 2: Thresholds - placeholder, will be generated by reasoning model
      // TODO: Replace with dynamic threshold detection via FDA/CPSC API
      const thresholds: RegulatoryThresholds = {
        employeeThresholds: {
          count: profile.employeeCount,
          triggers: {} // Will be populated dynamically by reasoning model
        },
        federalContractor: false,
        stateSpecificTriggers: {}
      };

      // Step 3: Recommendations - placeholder, will be generated by reasoning model
      // TODO: Replace with dynamic recommendation generation via reasoning model
      const recommendations = {
        criticalCompliance: [] as string[],
        likelyRequirements: [] as string[],
        investigateFurther: [] as string[]
      };

      // Step 4: Calculate data quality
      const dataQuality = this.assessDataQuality(profile);

      // Return complete intelligence
      return {
        input,
        profile,
        thresholds,
        dataQuality,
        analysisDate: new Date(),
        recommendations
      };
    } catch (error) {
      console.error('Company analysis error:', error);
      throw error;
    }
  }

  /**
   * Build comprehensive company profile from multiple sources
   *
   * The LLM will intelligently gather data from:
   * - SEC EDGAR filings for public companies (10-K, 10-Q, proxy statements)
   * - Company websites for products, services, and certifications
   * - State business registrations and news articles
   * - Government contracts databases (SAM.gov, USASpending.gov)
   *
   * For PUBLIC companies, the LLM will:
   * - Search SEC EDGAR for latest 10-K filing
   * - Extract employee count from Item 1 (Business Description)
   * - Find facility locations from Item 2 (Properties)
   * - Identify risks and compliance mentions in Item 1A (Risk Factors)
   *
   * For PRIVATE companies, the LLM will:
   * - Analyze news articles and press releases
   * - Check industry databases and directories
   * - Estimate based on similar companies in the industry
   */
  private async buildCompanyProfile(input: CompanyInput): Promise<CompanyProfile> {
    const dataSources: DataSource[] = [];

    // Determine if company is likely public (could be enhanced with actual check)
    const isLikelyPublic = input.companyName.toLowerCase().includes('inc') ||
                          input.companyName.toLowerCase().includes('corp');

    // Gather data from all sources in parallel
    const [
      companyData,   // LLM analyzes SEC filings or other public sources
      websiteData,   // Parse company website for products/services
      locations,     // Find locations from various sources
      newsData,      // Search news and press releases
    ] = await Promise.all([
      webScrapingService.analyzeCompanyWithLLM(input.companyName, isLikelyPublic),
      webScrapingService.scrapeCompanyWebsite(input.website),
      webScrapingService.findCompanyLocations(input.companyName, input.state),
      webScrapingService.searchNewsAndPress(input.companyName),
    ]);
    
    // Track data sources
    if (companyData.employeeCount) {
      dataSources.push({
        source: isLikelyPublic ? 'SEC Filings' : 'Public Records',
        dataPoints: ['employeeCount', 'industries', 'locations'],
        fetchDate: new Date(),
        reliability: isLikelyPublic ? 'high' : 'medium'
      } as DataSource);
    }
    if (websiteData.products) {
      dataSources.push(
        webScrapingService.createDataSource('Company Website', ['products', 'services', 'certifications'])
      );
    }
    
    // Build complete profile
    // NOTE: likelyChemicals, likelyProcesses, likelyHazards will be
    // populated dynamically by reasoning model based on NAICS + recall data
    const profile: CompanyProfile = {
      // Basic info
      companyName: input.companyName,
      naicsCode: input.naicsCode,
      website: input.website,
      primaryState: input.state,

      // From LLM analysis (SEC filings, public records, etc.)
      employeeCount: companyData.employeeCount || 0, // 0 indicates not found
      employeeRange: companyData.employeeRange || 'Unknown',
      industries: companyData.industries || [],
      yearEstablished: companyData.yearEstablished,

      // From website
      products: websiteData.products || [],
      services: websiteData.services || [],
      certifications: websiteData.certifications || [],

      // From various sources
      locations: locations,
      customerTypes: newsData.customerTypes,
      annualRevenue: newsData.annualRevenue,
      parentCompany: newsData.parentCompany,

      // TODO: Will be populated by reasoning model dynamically
      likelyChemicals: [],
      likelyProcesses: [],
      likelyHazards: [],
    };

    return profile;
  }

  // NOTE: inferFromNAICS and generateRecommendations have been removed
  // All inference and recommendations will be generated dynamically
  // by the reasoning model based on recall data and company profile

  /**
   * Assess quality of gathered data
   */
  private assessDataQuality(profile: CompanyProfile): DataQuality {
    let qualityScore = 0;
    const maxScore = 100;
    
    // Score based on data completeness
    if (profile.employeeCount > 0) qualityScore += 20;
    if (profile.products.length > 0) qualityScore += 15;
    if (profile.locations.length > 0) qualityScore += 15;
    if (profile.certifications.length > 0) qualityScore += 10;
    if (profile.customerTypes.length > 0) qualityScore += 10;
    if (profile.yearEstablished) qualityScore += 10;
    
    // Determine confidence levels
    const confidence = {
      employeeCount: profile.employeeRange ? 'range' as const : 'estimated' as const,
      locations: profile.locations.length > 1 ? 'complete' as const : 'primary-only' as const,
      products: profile.products.length > 3 ? 'comprehensive' as const : 
                profile.products.length > 0 ? 'sampling' as const : 'basic' as const,
      epaData: 'not-found' as const
    };
    
    // Create data sources list
    const sources: DataSource[] = [];
    
    if (profile.employeeCount) {
      sources.push({
        source: 'LinkedIn',
        dataPoints: ['employeeCount', 'industries'],
        fetchDate: new Date(),
        reliability: 'medium'
      });
    }
    
    if (profile.products.length > 0) {
      sources.push({
        source: 'Company Website',
        dataPoints: ['products', 'services', 'certifications'],
        fetchDate: new Date(),
        reliability: 'high'
      });
    }
    
    return {
      confidence,
      sources,
      qualityScore,
      lastUpdated: new Date()
    };
  }

  /**
   * Get cached analysis if available
   */
  async getCachedAnalysis(companyName: string): Promise<CompanyIntelligence | null> {
    // In production, would check Redis or database
    // For now, return null (no cache)
    return null;
  }

  /**
   * Save analysis to cache
   */
  async cacheAnalysis(intelligence: CompanyIntelligence): Promise<void> {
    // In production, would save to Redis or database
    console.log(`Would cache analysis for ${intelligence.input.companyName}`);
  }
}

export const companyAnalyzer = new CompanyAnalyzer();